### ISSUE TITLE
Correct grammar

### ISSUE THREAD

**Issue by luqmanoop** [dwyl/technical-glossary#30]
`keywords` not `key words`. Reference https://github.com/dwyl/technical-glossary#what

**Comment by nelsonic** [comment]
@codeshifu thank you for reporting this typo! If you have time to fix it with a PR, please do. 👍

**Comment by Cleop** [comment]
@codeshifu thanks for taking interest in the repo 😊, I'm not sure that this amendment needs to be made however.

I've done a little research and it appears to me that:

> Key word is a word that is key/important.
Keyword is a search-related word.

> you can spell it either as one word or two; both are considered correct
https://forum.wordreference.com/threads/key-word-vs-keyword.3088253/
https://ell.stackexchange.com/questions/115815/is-it-okay-to-use-key-words-as-two-separate-words-to-indicate-keywords

In the context that we are using the term we are referring to a word that is key/important not in a search context. So I would suggest this issue can be closed?

**Comment by luqmanoop** [comment]
@Cleop Cool 👍

**Comment by nelsonic** [comment]
Closing as @Cleop addressed above. ✅ ❤️
