### ISSUE TITLE
Define "SPIKE": What is it? Why do we do them? What is the outcome?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technical-glossary#40]
https://en.wikipedia.org/wiki/Spike_(software_development)

**Comment by iteles** [comment]
Linked to https://github.com/dwyl/contributing/issues/34

**Comment by nelsonic** [comment]
***Glad*** I opened this issue to capture the requirement to define this term. 📝 
**_Really_ wish _anyone_ `else`** could have written it up so I didn't have to ... 🙏

**Comment by nelsonic** [comment]
https://github.com/dwyl/technical-glossary/blob/b2075624754a29b456182fb9bd37a0abe2fd066d/README.md#spike

PR: #41
