### ISSUE TITLE
New word: hexadecimal 

### ISSUE THREAD

**Issue by Cleop** [dwyl/technical-glossary#9]
- [x] add definition for new word: hexadecimal

https://en.wikipedia.org/wiki/Hexadecimal

**Comment by nelsonic** [comment]
[https://github.com/dwyl/technical-glossary#hexadecimal](https://github.com/dwyl/technical-glossary/tree/677e6a1fd4044ea9752aae75cfc483636f8b5b84#hexadecimal)
